name: flutter_mobile
description: Student Portal - Flutter Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "../mobile/assets/icon.png"
  adaptive_icon_background: "#eef2ff"
  adaptive_icon_foreground: "../mobile/assets/android-icon-foreground.png"
  adaptive_icon_monochrome: "../mobile/assets/android-icon-monochrome.png"

flutter:
  uses-material-design: true
